.ALIASES
V_V1            V1(+=N00172 -=0 ) CN @B2.SCHEMATIC1(sch_1):INS40@SOURCE.VDC.Normal(chips)
R_R1            R1(1=N00172 2=N00179 ) CN @B2.SCHEMATIC1(sch_1):INS65@ANALOG.R.Normal(chips)
R_R2            R2(1=0 2=N00179 ) CN @B2.SCHEMATIC1(sch_1):INS90@ANALOG.R.Normal(chips)
R_R3            R3(1=0 2=N00179 ) CN @B2.SCHEMATIC1(sch_1):INS106@ANALOG.R.Normal(chips)
L_L1            L1(1=N00183 2=N00179 ) CN @B2.SCHEMATIC1(sch_1):INS131@ANALOG.L.Normal(chips)
X_U1            U1(1=0 2=N00183 ) CN @B2.SCHEMATIC1(sch_1):INS156@EVAL.Sw_tClose.Normal(chips)
.ENDALIASES
